"""Fix association tables for M2M

Revision ID: 998ad7d9e6ef
Revises: b5f96f1a5fbe
Create Date: 2023-01-23 13:00:15.027552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998ad7d9e6ef'
down_revision = 'b5f96f1a5fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint('post_tags_tag_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.drop_constraint('roles_users_role_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roles_users_role_id_fkey', 'role', ['role_id'], ['id'])

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_tags_tag_id_fkey', 'tag', ['tag_id'], ['id'])

    # ### end Alembic commands ###
